name: app_melivra
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^4.2.0

  # Gerência de Estados
  mobx: ^2.0.5
  flutter_mobx: ^2.0.2

  # Utils
  equatable: ^2.0.3
  dartz: ^0.10.0
  version: ^2.0.0
  google_sign_in: ^5.2.1

  # Images
  flutter_svg: ^0.23.0+1

  # Firebase
  firebase_core: ^1.10.0
  firebase_analytics: ^8.3.4
  firebase_crashlytics: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  mobx_codegen: ^2.0.4
  build_runner: ^2.1.5
  mocktail: ^0.2.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

fonts:
  - family: Quicksand
    fonts:
      - asset: lib/assets/fonts/Quicksand_Light.ttf
        weight: 300
      - asset: lib/assets/fonts/Quicksand_Regular.ttf
        weight: 400
      - asset: lib/assets/fonts/Quicksand_Medium.ttf
        weight: 500
      - asset: lib/assets/fonts/Quicksand_SemiBold.ttf
        weight: 600
      - asset: lib/assets/fonts/Quicksand_Bold.ttf
        weight: 700

scripts:
  build_apk: flutter build apk --split-per-abi
  build_bundle: flutter build appbundle
  mobx: flutter pub run build_runner build
  mobx_delete: flutter pub run build_runner build --delete-conflicting-outputs
  mobx_watch: flutter pub run build_runner watch
  mobx_clean: flutter pub run build_runner clean
  package_outdated: flutter pub outdated
  test_coverage: flutter test --coverage
