name: app_melivra
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3

  # Gerência de Estados
  mobx: ^2.0.5
  flutter_mobx: ^2.0.2

  # Utils
  equatable: ^2.0.3
  dartz: ^0.10.0
  version: ^3.0.2
  google_sign_in: ^5.2.1
  package_info: ^2.0.2
  device_info: ^2.0.3
  connectivity_plus: ^3.0.2

  # Images
  flutter_svg: ^1.1.6

  # Firebase
  firebase_core: ^2.1.1
  firebase_storage: ^11.0.3
  firebase_analytics: ^10.0.3
  firebase_crashlytics: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  mobx_codegen: ^2.0.4
  build_runner: ^2.1.5
  mocktail: ^0.3.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700

scripts:
  build_apk: flutter build apk --split-per-abi
  build_bundle: flutter build appbundle
  mobx: flutter pub run build_runner build
  mobx_delete: flutter pub run build_runner build --delete-conflicting-outputs
  mobx_watch: flutter pub run build_runner watch
  mobx_clean: flutter pub run build_runner clean
  package_outdated: flutter pub outdated
  test_coverage: flutter test --coverage
