name: app_melivra
description: Aplicativo para avaliação de professores

publish_to: "none"

version: 1.1.0+12

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^6.4.1

  # DB
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Network
  dio: ^5.2.1+1

  # Gerência de Estados
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1

  # Utils
  equatable: ^2.0.3
  dartz: ^0.10.0
  version: ^3.0.2
  package_info_plus: ^8.3.1
  device_info_plus: ^11.5.0
  connectivity_plus: ^6.1.5
  jwt_decoder: ^2.0.1
  sleek_circular_slider: ^2.0.1
  fluttertoast: ^8.1.2
  url_launcher: ^6.1.7
  profanity_filter: ^2.0.0
  pin_code_fields: ^8.0.1
  pinput: ^5.0.1
  tutorial_coach_mark: ^1.2.9
  font_awesome_flutter: ^10.7.0
  google_sign_in: ^7.1.1
  # Images
  flutter_svg: ^2.0.7

  # Firebase
  firebase_core: ^4.0.0
  firebase_storage: ^13.0.0
  firebase_analytics: ^12.0.0
  firebase_crashlytics: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  mobx_codegen: ^2.0.4
  mocktail: ^1.0.4
  build_runner: ^2.1.5

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700

scripts:
  build_apk: flutter build apk --split-per-abi
  build_bundle: flutter build appbundle
  mobx: flutter pub run build_runner build
  mobx_delete: flutter pub run build_runner build --delete-conflicting-outputs
  mobx_watch: flutter pub run build_runner watch
  mobx_clean: flutter pub run build_runner clean
  package_outdated: flutter pub outdated
  test_coverage: flutter test --coverage
